### ISSUE TITLE
`next/font` error: Cannot be used within pages/_document.js.

### ISSUE THREAD

**Issue by auragit** [mauriciobraz/next.js-telegram-webapp#1]
Cannot run the project with the given instructions. 

This is the error I get:
`- wait compiling...
- error src/pages/_document.tsx
`next/font` error:
Cannot be used within pages/_document.js.`

**Comment by mauriciobraz** [comment]
Try using `src/pages/_app.tsx` instead `src/pages/_document.tsx` for loading the fonts.

https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#google-fonts
